#!/bin/bash

# Expand aliases for non-interactive shell
shopt -s expand_aliases

# Fail pipeline when variable is not set or individual command has an non-zero exitcode.
set -euo pipefail

# Show which commands are being run
set -x

# Chown the checked out files
sudo chown -R domjudge:domjudge .

# Shared constants between jobs
DIR=$(pwd)
GITSHA=$(git rev-parse HEAD || true)
export DIR
export GITSHA
export PS4='(${BASH_SOURCE}:${LINENO}): - [$?] $ '
export LOGFILE="/opt/domjudge/domserver/webapp/var/log/prod.log"

# Functions to annotate the Github actions logs
alias trace_on='set -x'
alias trace_off='{ set +x; } 2>/dev/null'

section_start_internal  () {
    echo "::group::$1"
    trace_on
}

section_end_internal () {
    echo "::endgroup::"
    trace_on
}

alias section_start='trace_off ; section_start_internal '
alias section_end='trace_off ; section_end_internal '

# Shared storage for all artifacts
export ARTIFACTS="$DIR/artifacts"
mkdir -p "$ARTIFACTS"

function show_phpinfo() {
    phpversion=$1
    section_start phpinfo
    update-alternatives --set php /usr/bin/php"${phpversion}"
    php -v
    php -m
    section_end phpinfo
}

function log_on_err() {
    echo -e "\\n\\n=======================================================\\n"
    echo "Symfony log:"
    if sudo test -f "$LOGFILE" ; then
        sudo cat "$LOGFILE"
    fi
}

set -eux
