engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 60
  eslint:
    enabled: true
    checks:
      no-alert:
        enabled: false
    exclude_fingerprints:
## Ignore 'exit(1)' in test-hello.js:
    - 868673da0d2ee8f1ff139f0a004b166f
## Ignore IE <= 8 overwrite of catch variable 'e':
    - 2bae39c1743204c63f6ba7028b612199
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: ".phpmd-ruleset.xml"
    exclude_fingerprints:
## Ignore some proper uses of 'exit()':
    - 133867cfc661d32c08cde20fdfdbbc4b
    - aa5c13777d476ad6ae1ac827f13fbe33
    - b37f144cecd350adf1332a6fcd6ace73
    - 874c8ca5aff6ed6343b0b81b872835e8
    - e1302c82b896beb140d4bdad80e2ab70
    - 454fe7ae0b787e00690f382c2cc31553

  shellcheck:
## Disable since we already check it ourselves, and the tests are not
## configurable on Code Climate.
    enabled: false

## Simply include all files for GPA ratings:
ratings:
  paths:
  - "**"

## Excluded files, e.g. external libraries:
exclude_paths:
- "config.guess"
- "config.sub"
- "install.sh"
- "lib/vendor/"
- "www/js/ace/"
- "www/js/flot/"
- "www/js/jquery*.js"
- "www/js/jscolor.js"
- "www/js/js.cookie*.js"
- "www/js/sorttable.js"
- "www/js/tabber.js"
