path_classifiers:
  test:
    - tests
  library:
    - lib/vendor
    - webapp/public/js/ace
    - "webapp/public/js/bootstrap-toggle.*"
    - webapp/public/js/coloris.min.js
  docs:
    - doc
queries:
  - exclude: cpp/fixme-comment
extraction:
  cpp:
    prepare:
      packages:
        - php-curl
        - php-gd
        - php-intl
        - php-mbstring
        - php-mysql
        - php-xml
        - php-zip
        - php-cli
    configure:
      command:
        - mkdir -p $LGTM_WORKSPACE/bin
        - export PATH=$LGTM_WORKSPACE/bin:$PATH
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - HASH="$(wget -q -O - https://composer.github.io/installer.sig)"
        - php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        - php composer-setup.php --install-dir=$LGTM_WORKSPACE/bin --filename=composer
        - make dist DOC_BUILD_ENABLED=no
        - ./configure --disable-doc-build
    index:
      build_command:
        - make build
