codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 2%
    patch:
      default:
        target: 0%
        threshold: 2%
comment: false
