#!/bin/sh
# $Id$
#
# This script is called by dbconfig-common on package installation.
# It's a bit of a hack to set up multiple users for DOMjudge which
# have different privileges. dbconfig-common can only create one
# user. The hack is that we source a part of dbconfig-common into
# the script so we have a way to access the database as the
# db admin account.

set -e

# Create secrets file with appropriate permissions.

touch /etc/domjudge/dbpasswords.secret
chgrp www-data /etc/domjudge/dbpasswords.secret
chmod 0640 /etc/domjudge/dbpasswords.secret

# Source dbconfig-common functions and the credentials of the already
# created user.
. /etc/dbconfig-common/domjudge-domserver.conf
. /usr/share/dbconfig-common/internal/mysql

# Create accounts for the roles we need (jury was already done)

ROLES='team public plugin'
FROM='% localhost'
for role in $ROLES ; do
	user="domjudge_${role}"
	pass=`env LANG=C LC_ALL=C tr -dc "[:alnum:]" < /dev/urandom | dd bs=1 count=12 2>/dev/null`

# Need to add both '%' and 'localhost' as entries, because a default
# fresh MySQL installation has a Host='localhost',User='' entry which
# is more specific than Host='%' and thus leads to Access Denied errors.
	for from in $FROM; do
		dbc_mysql_exec_command "CREATE USER '$user'@'$from' IDENTIFIED BY '$pass'"
	done

	echo "${role}:$dbc_dbserver:$dbc_dbname:$user:$pass" >> /etc/domjudge/dbpasswords.secret
done

# domjudge_jury@localhost was already created by dbconfig-common;
# only need to add domjudge_jury@%.
dbc_mysql_exec_command "CREATE USER '$dbc_dbuser'@'%' IDENTIFIED BY '$dbc_dbpass'"
echo "jury:$dbc_dbserver:$dbc_dbname:$dbc_dbuser:$dbc_dbpass" >> /etc/domjudge/dbpasswords.secret

dbc_mysql_exec_command "FLUSH PRIVILEGES"

