#!/bin/sh
# $Id: dj_make_chroot 2903 2009-10-09 07:42:22Z eldering $

# Read command-line parameters:
CHROOTDIR=/var/lib/domjudge/javachroot
# To prevent (libc6) upgrade questions:
export DEBIAN_FRONTEND=noninteractive

if [ `id -u` != 0 ]; then
    echo "Warning: you probably need to run this program as root."
fi

# Prevent perl locale warnings in the chroot:
export LC_ALL=C

chroot "$CHROOTDIR" /bin/sh -c "apt-get update && apt-get upgrade"
chroot "$CHROOTDIR" /bin/sh -c "apt-get clean"
# Remove unnecessary setuid bits
chroot "$CHROOTDIR" /bin/sh -c "chmod a-s /usr/bin/wall /usr/bin/newgrp \
	/usr/bin/chage /usr/bin/chfn /usr/bin/chsh /usr/bin/expiry \
	/usr/bin/gpasswd /usr/bin/passwd /usr/lib/pt_chown \
	/bin/su /bin/mount /bin/umount /sbin/unix_chkpwd"

exit 0
