# Configuration file for bash-shell scripts
# $Id: config.template.sh 453 2004-08-29 12:48:29Z nkp0405 $

### AUTOGENERATE HEADER START ###
#
# This configuration file was automatically generated
# on Wed Feb 23 18:40:21 CET 2005 on host 'janos'.
#
# Do not edit this file by hand! Instead, edit parts of this
# file which are outside the 'AUTOGENERATE HEADER' and
# 'GLOBAL CONFIG INCLUDE' tags in the templates 'config.template.*'.
#
# Configuration options inside 'GLOBAL CONFIG INCLUDE' tags
# should be edited in the main configuration file 'global.cfg'
# and then be included here by running the 'generate_config.sh'
# command.
#
### AUTOGENERATE HEADER END ###

# Loglevels (as defined in syslog.h)
LOG_EMERG=0
LOG_ALERT=1
LOG_CRIT=2
LOG_ERR=3
LOG_WARNING=4
LOG_NOTICE=5
LOG_INFO=6
LOG_DEBUG=7

# Exit/error codes:
E_CORRECT=0
E_COMPILE=1
E_TIMELIMIT=2
E_RUNERROR=3
E_OUTPUT=4
E_ANSWER=5
E_INTERN=127 # Internal script error

### GLOBAL CONFIG INCLUDE START ###
DOMJUDGE_VERSION="0.2.0"
SYSTEM_ROOT="/home/mensjes/eldering/svn/domjudge"
OUTPUT_ROOT="/home/mensjes/eldering/domjudge/output"
INPUT_ROOT="/home/mensjes/eldering/domjudge/input"
INCOMINGDIR="/home/mensjes/eldering/domjudge/output/incoming"
SUBMITDIR="/home/mensjes/eldering/domjudge/output/sources"
JUDGEDIR="/home/mensjes/eldering/domjudge/output/judging"
LOGDIR="/home/mensjes/eldering/domjudge/output/log"
CHROOT_PREFIX="/home/mensjes/eldering/domjudge/output/judging"
WEBSERVER="domjudge.a-eskwadraat.nl"
WEBBASEURI="http://domjudge.a-eskwadraat.nl/eldering/"
SUBMITSERVER="domjudge.a-eskwadraat.nl"
SUBMITPORT=9147
DBSERVER="localhost"
DBNAME="nkpjury"
SCP_HOST="localhost"
VALID_USERS="eldering,test,nobody"
RUNUSER="nobody"
COMPILETIME=30
SOURCESIZE=256
MEMLIMIT=65536
FILELIMIT=4096
PROCLIMIT=8
USERSUBMITDIR=".submit"
USERPERMFILE=0600
USERPERMDIR=0700
WARN_MTIME=5
PENALTY_TIME=20
LANG_EXTS="C,c C++,cpp,cc,c++ Java,java Pascal,pas,p"
BEEP_ERROR="-D 200  -r 3  -f 550 -l 500 -n -d 1000 -r 10 -f 300 -l 400"
BEEP_SUBMIT="-f 400 -l 100 -n -f 400 -l 70"
BEEP_ACCEPT="-f 400 -l 100 -n -f 500 -l 70"
BEEP_REJECT="-f 400 -l 100 -n -f 350 -l 70"
DEBUG=0
### GLOBAL CONFIG INCLUDE END ###
