<?php

/* Configuration file for PHP-scripts
 * $Id: config.template.php 700 2004-11-20 11:05:04Z nkp0405 $
 */

/*** AUTOGENERATE HEADER START ***/
//
// This configuration file was automatically generated
// on Wed Feb 23 18:40:21 CET 2005 on host 'janos'.
//
// Do not edit this file by hand! Instead, edit parts of this
// file which are outside the 'AUTOGENERATE HEADER' and
// 'GLOBAL CONFIG INCLUDE' tags in the templates 'config.template.*'.
//
// Configuration options inside 'GLOBAL CONFIG INCLUDE' tags
// should be edited in the main configuration file 'global.cfg'
// and then be included here by running the 'generate_config.sh'
// command.
//
/*** AUTOGENERATE HEADER END ***/

/** Loglevels */
define_syslog_variables();
error_reporting(E_ALL);

/** Possible exitcodes from testsol and their meaning */
$EXITCODES = array (
	0	=>	'correct',
	1	=>	'compiler-error',
	2	=>	'timelimit',
	3	=>	'run-error',
	4	=>	'no-output',
	5	=>	'wrong-answer'
	);

/** Include MySQL database passwords from a separate file */
require('passwords.php');


/*** GLOBAL CONFIG INCLUDE START ***/
define('DOMJUDGE_VERSION', '0.2.0');
define('SYSTEM_ROOT', '/home/mensjes/eldering/svn/domjudge');
define('OUTPUT_ROOT', '/home/mensjes/eldering/domjudge/output');
define('INPUT_ROOT', '/home/mensjes/eldering/domjudge/input');
define('INCOMINGDIR', '/home/mensjes/eldering/domjudge/output/incoming');
define('SUBMITDIR', '/home/mensjes/eldering/domjudge/output/sources');
define('JUDGEDIR', '/home/mensjes/eldering/domjudge/output/judging');
define('LOGDIR', '/home/mensjes/eldering/domjudge/output/log');
define('CHROOT_PREFIX', '/home/mensjes/eldering/domjudge/output/judging');
define('WEBSERVER', 'domjudge.a-eskwadraat.nl');
define('WEBBASEURI', 'http://domjudge.a-eskwadraat.nl/eldering/');
define('SUBMITSERVER', 'domjudge.a-eskwadraat.nl');
define('SUBMITPORT', 9147);
define('DBSERVER', 'localhost');
define('DBNAME', 'nkpjury');
define('SCP_HOST', 'localhost');
define('VALID_USERS', 'eldering,test,nobody');
define('RUNUSER', 'nobody');
define('COMPILETIME', 30);
define('SOURCESIZE', 256);
define('MEMLIMIT', 65536);
define('FILELIMIT', 4096);
define('PROCLIMIT', 8);
define('USERSUBMITDIR', '.submit');
define('USERPERMFILE', 0600);
define('USERPERMDIR', 0700);
define('WARN_MTIME', 5);
define('PENALTY_TIME', 20);
define('LANG_EXTS', 'C,c C++,cpp,cc,c++ Java,java Pascal,pas,p');
define('BEEP_ERROR', '-D 200  -r 3  -f 550 -l 500 -n -d 1000 -r 10 -f 300 -l 400');
define('BEEP_SUBMIT', '-f 400 -l 100 -n -f 400 -l 70');
define('BEEP_ACCEPT', '-f 400 -l 100 -n -f 500 -l 70');
define('BEEP_REJECT', '-f 400 -l 100 -n -f 350 -l 70');
define('DEBUG', 0);
/*** GLOBAL CONFIG INCLUDE END ***/
