#!/bin/sh

create_pw_file()
{
	SCRIPT="$1"
	FILE="$2"

	if [ -f "$FILE" ]; then
		echo "Password file '$FILE' already exists, leaving untouched."
		return
	fi

	echo -n "Running '$SCRIPT'... "
	touch "$FILE"
	chmod go= "$FILE"
	$SCRIPT > "$FILE"
	echo "file '$FILE' created."
}

create_pw_file ./gendbpasswords dbpasswords.secret
create_pw_file ./genrestapicredentials restapi.secret
create_pw_file ./gensymfonysecret symfony_app.secret
create_pw_file ./genadminpassword initial_admin_password.secret
