#!/bin/sh

# Script to generate database passwords. Passwords will be written to stdout,
# you can redirect stdout to etc/dbpasswords.secret

# Exit on any error:
set -e

echo "# Randomly generated on host `hostname`, `date`"
echo "# Format: 'unused:<db_host>:<db_name>:<user>:<password>:<db_port>'"

printf "unused:localhost:domjudge:domjudge:%s:3306\n" \
	   $(head -c12 /dev/urandom | base64 | head -c16 | tr '/+' 'Aa')
