#!/bin/sh
# $Id$

# Script to generate database passwords. Passwords will be written to stdout,
# you can redirect stdout to etc/dbpasswords.secret

# Exit on any error:
set -e

for group in team jury public plugin; do
	printf "$group:localhost:domjudge:domjudge_$group:"
	head -c12 /dev/random | uuencode -m /dev/stdout | tail -n +2 | \
		head -c16 | tr '/+' 'Aa'
	echo
done
