#!/bin/bash
# $Id$

# Script to generate specific config files for different languages
# from one global config file 'global.cfg'. This way all configuration
# data which is shared between different languages used in the system
# has to be changed in only one place: the global config file.
#
# Usage: generate_config.sh <extension>
#
# <extension> may be a complete filename (including path), but only
# the extension (after the last dot) is taken. A configuration file
# is then generated from 'config.template.<extension>' and 'global.cfg'
# into 'config.<extension>'.
#
#
# See 'global.cfg' for the syntax of that file.
#
# Syntax of the language specific templates:
#
# In these files different tags are used to specify parts of the files
# which are replaced by automatically generated content. Tags must
# exactly appear once with a 'START' and after that an 'END' suffix
# and different tags may not overlap. The next tags are defined:
#
# 'GLOBAL CONFIG INCLUDE'
#	Within these tags the content generated from the global config
#	file is placed. All previous content is removed.
#
# 'AUTOGENERATE HEADER'
#	Within these tags some information on the automatic generation of
#	the config file is placed. All previous content is removed.
#
# Content in the configuration templates outside of any tags is copied
# as is to the config file. Here language specific configuration data
# can be placed and other things you like...
#

shopt -s extglob

# Include '../bin' in path for 'tempfile'
PATH=../bin:$PATH

GLOBALCONF=global.cfg
LOCALCONF=config
LOCALTEMPLATE=config.template

CONFHEADTAG="AUTOGENERATE HEADER"
CONFMAINTAG="GLOBAL CONFIG INCLUDE"

# Maximum number of lines in config files
MAXLINES=1000

EXT=${1##*.}
TEMPLATE="$LOCALTEMPLATE.$EXT"
CONFIG="$LOCALCONF.$EXT"

case $EXT in
	h)    COMMENT='//';;
	sh)   COMMENT='#';;
	php)  COMMENT='//';;
	tex)  COMMENT='%';;
	*)		echo "Filetype '$EXT' is not supported."; exit 1;;
esac

if [ ! -r "$TEMPLATE" ]; then
	echo "Template '$TEMPLATE' does not exist."
	exit 1
fi

if [ ! -r "$GLOBALCONF" ]; then
	echo "Global config '$GLOBALCONF' does not exist."
	exit 1
fi

# Store config generated from global config here
TMPMAIN=`tempfile -p "main" -s ".$EXT"`
TMPHEAD=`tempfile -p "head" -s ".$EXT"`

COMMANDLINE="$0 $@"


# Generate language specific config from global config
exec 3<$GLOBALCONF

OLDIFS=$IFS

declare VARDEF VARATTR VARNAME VALUE
declare ATTR ATTR_STRING ATTR_EVAL

LINENR=0
while IFS='='; read VARDEF VALUE <&3; do
	IFS=$OLDIFS
	((LINENR++))
	
	# Ignore comments and whitespace only lines
	if [[ "$VARDEF" == *([:space:]) || "$VARDEF" == '#'* ]]; then
		continue
	fi

	ATTR_STRING=0
	ATTR_EVAL=0
	# Check for attributes
	if [[ "$VARDEF" == *'['* ]]; then
		VARATTR=${VARDEF##*'['}
		if [[ "$VARATTR" != +([a-z])*(,+([a-z]))']' ]]; then
			echo "Parse error on line $LINENR!"
			exit 1
		fi
		VARATTR=${VARATTR%']'}
		IFS="$IFS,"
		for ATTR in $VARATTR; do
			case "$ATTR" in
			"string")	ATTR_STRING=1;;
			"eval")		ATTR_EVAL=1;;
			*)			echo "Unknown variable attribute '$ATTR' on line $LINENR!"
						exit 1;;
			esac
		done
		IFS=$OLDIFS
	fi
	VARNAME=${VARDEF%%'['*}
	if [[ "$VARNAME" != [A-Za-z]*([A-Za-z0-9_]) ]]; then
		echo "Invalid variable name '$VARNAME' on line $LINENR!"
		exit 1
	fi

	if [ $ATTR_EVAL -ne 0 ]; then
		eval VALUE="$VALUE"
	fi

	if [ $ATTR_STRING -ne 0 ]; then
		case $EXT in
		h)    echo "#define $VARNAME \"$VALUE\""   >>$TMPMAIN;;
		sh)   echo "$VARNAME=\"$VALUE\""           >>$TMPMAIN;;
		php)  echo "define('$VARNAME', '$VALUE');" >>$TMPMAIN;;
		tex)  echo "\\def\\$VARNAME{$VALUE}"       >>$TMPMAIN;;
		esac
	else
		case $EXT in
		h)    echo "#define $VARNAME $VALUE"       >>$TMPMAIN;;
		sh)   echo "$VARNAME=$VALUE"               >>$TMPMAIN;;
		php)  echo "define('$VARNAME', $VALUE);"   >>$TMPMAIN;;
		tex)  echo "\\def\\$VARNAME{$VALUE}"       >>$TMPMAIN;;
		esac
	fi

	if set | grep ^${VARNAME}= &>/dev/null; then
		echo "Variable '$VARNAME' already in use on line $LINENR!"
		exit 1
	fi

	eval $VARNAME="'$VALUE'"
done

exec 3<&-

# Generate header tags include
cat >>$TMPHEAD <<EOF
$COMMENT
$COMMENT This configuration file was automatically generated
$COMMENT on `date` on host '$HOSTNAME'.
$COMMENT
$COMMENT Do not edit this file by hand! Instead, edit parts of this
$COMMENT file which are outside the '$CONFHEADTAG' and
$COMMENT '$CONFMAINTAG' tags in the templates '$LOCALTEMPLATE.*'.
$COMMENT
$COMMENT Configuration options inside '$CONFMAINTAG' tags
$COMMENT should be edited in the main configuration file '$GLOBALCONF'
$COMMENT and then be included here by running the '`basename $0`'
$COMMENT command.
$COMMENT
EOF

function config_include ()
{
	local TAG=$1
	local CFGFILE=$2
	local TAGFILE=$3

	local TMPFILE=`tempfile -p 'cfg' -s '.tmp'`

	local NSTART NEND

	NSTART=`grep "$TAG START" $CFGFILE | wc -l`
	NEND=`  grep "$TAG END"   $CFGFILE | wc -l`
	if [ $NSTART -ne 1 -o $NEND -ne 1 ]; then
		echo "Incorrect number of '$TAG' START and/or END tags in $CFGFILE!"
		exit 1
	fi
	if [ `grep -A $MAXLINES "$TAG START" $CFGFILE | grep "$TAG END" | wc -l` -ne 1 ]; then
		echo "'$TAG' END tag does not close START tag in $CFGFILE!"
		exit 1
	fi

	grep -B $MAXLINES "$TAG START" $CFGFILE >$TMPFILE
	cat $TAGFILE >>$TMPFILE
	grep -A $MAXLINES "$TAG END"   $CFGFILE >>$TMPFILE
	cp $TMPFILE $CFGFILE

	rm -f $TMPFILE
}

cp -a $TEMPLATE $CONFIG

config_include $CONFHEADTAG $CONFIG $TMPHEAD
config_include $CONFMAINTAG $CONFIG $TMPMAIN

rm -f $TMPHEAD $TMPMAIN

exit 0
