#!/bin/sh
# $Id$

# Generate apache.conf from apache.template.conf.
# Replaces text beteen 'AUTOGENERATE HEADER START/END' tags with
# autogenerated message and fills in correct values for DOMjudge
# locations from configuration.

# Exit on any error:
set -e

CONFIG=apache.conf
TEMPLATE=apache.template.conf

COMMENT="#"
CONFHEADTAG="AUTOGENERATE HEADER"

# Maximum number of lines in config files
MAXLINES=1000

if [ ! -r "$TEMPLATE" ]; then
	echo "Template '$TEMPLATE' does not exist."
	exit 1
fi

# Store config generated from global config here
TMPHEAD=head.apache.new

# Clean any previous tempfiles left:
rm -f $TMPHEAD

COMMANDLINE="$0 $@"

# Include (shell-version) of config for substitution of variables:
. config.sh

# Parse DOMjudge sub-directory location from WEBBASEURI:
WEBSUBDIR=`echo "$WEBBASEURI" | sed "s!^.*$WEBSERVER[^/]*/\(.*\)/!\1!"`

# Generate header tags include
cat >>$TMPHEAD <<EOF
$COMMENT
$COMMENT This configuration file was automatically generated
$COMMENT with command '$COMMANDLINE'
$COMMENT on `date` on host '`hostname`'.
$COMMENT
$COMMENT Edit this file to suit your need; see $TEMPLATE
$COMMENT for more information.
$COMMENT
EOF

config_include ()
{
	TAG=$1
	CFGFILE=$2
	TAGFILE=$3

	TMPFILE=$CFGFILE.new

	NSTART=`grep "$TAG START" $CFGFILE | wc -l`
	NEND=`  grep "$TAG END"   $CFGFILE | wc -l`
	if [ $NSTART -ne 1 -o $NEND -ne 1 ]; then
		echo "Incorrect number of '$TAG' START and/or END tags in $CFGFILE!"
		exit 1
	fi
	if [ `grep -A $MAXLINES "$TAG START" $CFGFILE | grep "$TAG END" | wc -l` -ne 1 ]; then
		echo "'$TAG' END tag does not close START tag in $CFGFILE!"
		exit 1
	fi

	grep -B $MAXLINES "$TAG START" $CFGFILE >$TMPFILE
	cat $TAGFILE >>$TMPFILE
	grep -A $MAXLINES "$TAG END"   $CFGFILE >>$TMPFILE
	mv $TMPFILE $CFGFILE
}

eval echo "\"`cat $TEMPLATE`\"" > $CONFIG

config_include "$CONFHEADTAG" $CONFIG $TMPHEAD

rm -f $TMPHEAD

exit 0
