#!/bin/sh

# Script to generate REST API credentials. These will be written to stdout,
# you can redirect stdout to etc/restapi.secret

# Exit on any error:
set -e

echo "# Format: '<API url> <user> <password>'"

printf "http://localhost/domjudge/api	judgehost	"
        head -c12 /dev/urandom | base64 | head -c16 | tr '/+' 'Aa'
echo
