#!/bin/sh

# Script to generate an APP_SECRET for symfony, which will be included
# in the .env.local.php file together with database credentials.

head -c20 /dev/urandom | base64 | head -c20 | tr '/+' 'Aa'
echo
