#!/bin/sh

# Prolog compile wrapper-script for 'compile.sh'.
# See that script for syntax and more info.

DEST="$1" ; shift
MEMLIMIT="$1" ; shift
MAINSOURCE="${ENTRY_POINT:-$1}"
COMPILESCRIPTDIR="$(dirname "$0")"

exec swipl "$COMPILESCRIPTDIR/compile.plg" "$MAINSOURCE" "$DEST"

exit 0
