.\" Copyright (C) 2009 Red Hat, Inc. All Rights Reserved.
.\" Written by Jan Safranek <jsafrane@redhat.com>

.TH CGDELETE  1 2009-10-26 "Linux" "libcgroup Manual"
.SH NAME

cgdelete \- remove control group(s)

.SH SYNOPSIS
\fBcgdelete\fR [\fB-h\fR] [\fB-r\fR] [\fB-b\fR] [[\fB-g\fR]
<\fIcontrollers\fR>:\fI<path\fR>] ...

.SH DESCRIPTION
The \fBcgdelete\fR
program removes all specified control groups.

.TP
.B -b
ignores the default systemd delegated hierarchy path and
constructs the path of the control groups relative to the
cgroup root hierarchy.

.TP
.B [-g] <controllers>:<path>
Defines the control group to delete. Multiple control groups may be
specified.
.B -g
is optional.

.TP
.B -h, --help
Display this help and exit.

.TP
.B -r, --recursive
Recursively remove all subgroups.

.SH ENVIRONMENT VARIABLES
.TP
.B CGROUP_LOGLEVEL
controls verbosity of the tool. Allowed values are \fBDEBUG\fR,
\fBINFO\fR, \fBWARNING\fR or \fBERROR\fR.

.SH EXAMPLES
.TP
.B cgdelete -g cpu,devices:/test
remove control group test from hierarchies containing cpu and device controllers


.SH SEE ALSO
cgcreate (1), lscgroup (1)
