.\" Copyright (C) 2006 Red Hat, Inc. All Rights Reserved.
.\" Written by Ivana Varekova <varekova@redhat.com>.

.TH CGRED.CONF  5 2009-03-16 "Linux" "libcgroup Manual"
.SH NAME
cgred.conf \- libcgroup configuration file
.SH DESCRIPTION
\fBcgred.conf\fR is cgred service configuration file.
In this file there could be defined several internal values.
Defining anything else in this file will cause the
CGroup Rules Daemon program to fail.
.TP

\fBCONFIG_FILE\fR
specifies the configuration file for cgred service

.TP
\fBLOG_FILE\fR
variable specifies the file to which logs will be written
(by default they are not sent to a file but to syslog)

.TP
\fBNODAEMON\fR
if it is equal to "--nodaemon" then
run cgred in non-daemon mode

.TP
\fBLOG\fR
define the verbosity of logging. Accepted values are '-v', '-vv', '-q'
and '--nolog'.
.LP


.SH FILES
.LP
.PD .1v
.TP 20
.B /etc/cgred.conf
.TP
default libcgroup configuration file
.PD .

.SH SEE ALSO
cgrules.conf (5),
cgconfig.conf (5), cgrules.d (5)




