.\" Copyright (C) 2009 Red Hat, Inc. All Rights Reserved.
.\" Written by Ivana Hutarova Varekova <varekova@redhat.com>

.TH CGSET  1 2009-03-15 "Linux" "libcgroup Manual"
.SH NAME

cgset \- set the parameters of given cgroup(s)

.SH SYNOPSIS
\fBcgset\fR [\fB-b\fR] [\fB-r\fR <\fIname=value\fR>] <\fBcgroup_path\fR> ...
.br
\fBcgset\fR [\fB-b\fR] \fB--copy-from\fR <\fIsource_cgroup_path\fR> <\fBcgroup_path\fR> ...

.SH DESCRIPTION
Set the parameters of input cgroups.

.TP
.B <path>
is the name of the cgroup which should be changed.
This parameter can be used multiple times.

.TP
.B -b
ignores the default systemd delegated hierarchy path and
constructs the path of the control groups relative to the
cgroup root hierarchy.

.TP
.B -r <name=value>
defines the name of the file to set and
the value which should be written to that file.
This parameter can be used multiple times.

.TP
.B --copy-from <source_cgroup_path>
defines the name of the cgroup whose parameters will be
copied to the input cgroup.

.SH ENVIRONMENT VARIABLES
.TP
.B CGROUP_LOGLEVEL
controls verbosity of the tool. Allowed values are \fBDEBUG\fR,
\fBINFO\fR, \fBWARNING\fR or \fBERROR\fR.

.SH EXAMPLES
.TP
.B cgset -r cpuset.cpus=0-1 student
set variable cpus in control group student (controller cpuset) to 0-1

.TP
.B cgset --copy-from group1/ group2/
copy all parameters of group group1 to group group2
(for all path where both cgroups are defined)


.SH SEE ALSO
cgrules.conf (1), cgcreate (1), cgget (1)
