.\" Copyright (C) 2009 Red Hat, Inc. All Rights Reserved.
.\" Written by Ivana Hutarova Varekova <varekova@redhat.com>

.TH LSCGROUP  1 2009-11-05 "Linux" "libcgroup Manual"
.SH NAME

lscgroup \- list all cgroups

.SH SYNOPSIS
\fBlscgroup\fR [[\fB-g\fR] <\fIcontrollers>:<path\fR>] [...]
.br
\fBlscgroup\fR [\fB-h|--help\fR]

.SH DESCRIPTION
List all/chosen cgroups.

.TP
.B <controllers>:<path>
defines the control groups whose subgroups will be shown.
If this parameter is not used, the command will
list all existing cgroups.

.SH ENVIRONMENT VARIABLES
.TP
.B CGROUP_LOGLEVEL
controls verbosity of the tool. Allowed values are \fBDEBUG\fR,
\fBINFO\fR, \fBWARNING\fR or \fBERROR\fR.

.SH EXAMPLES
.TP
.B lscgroup -g cpu:/
list all cgroups which are in hierarchy containing cpu controller

.TP
.B lscgroup -g cpu:/student
list all cgroups which are in hierarchy containing cpu controller
in subgroup student

.TP
.B lscgroup
list all cgroups which in all hierarchies

.SH NOTES
.TP
lscgroup is currently supported on cgroups v1 only.

.SH SEE ALSO
lssubsys (1), cgcreate (1), cgdelete (1),
cgconfig.conf (5)
