#!/bin/sh

for i in cpuset memory; do
	mkdir -p /cgroup/$i; mount -t cgroup -o$i $i /cgroup/$i/;
	mkdir /cgroup/$i/domjudge
done

chown -R analyst /cgroup/*/domjudge

cat /cgroup/cpuset/cpuset.cpus > /cgroup/cpuset/domjudge/cpuset.cpus
cat /cgroup/cpuset/cpuset.mems > /cgroup/cpuset/domjudge/cpuset.mems
