#!/bin/sh

# $1: absolute path to directory where run results are found, and where
#      evaluation can be stored
#     (default: 'diff', 'evaluation'. The latter can have 'OK',
#     'TIMEOUT', 'RUNERROR', etc)
# $2: absolute path to directory containing testcase data
#     (default: 'output', 'compare-script')
# stdin: do not touch
# stdout: do not touch
# stderr: Internal errors (will cause daemon to crash)
# exit code: 0 unless internal error

