#!/bin/sh

# $1: submission language code
# $2: absolute path to directory where compilation results are found
# $3: absolute path to directory containing testcase data
#     (default: 'input', 'timelimit')
# $4: absolute path to directory where to put run results
#     (default: 'output', 'stderr', 'runstatus'. The latter can have 'OK',
#     'TIMEOUT', 'RUNERROR', etc)
# stdin: do not touch
# stdout: do not touch
# stderr: Internal errors (will cause daemon to crash)
# exit code: 0 unless internal error
