services:
  domjudge.domjudge:
    class: DOMJudgeBundle\Service\DOMJudgeService
    arguments: [ "@doctrine.orm.entity_manager", '@request_stack', '@service_container' ]

  domjudge.twigextension:
    class: DOMJudgeBundle\Twig\TwigExtension
    public: false
    arguments: ['@domjudge.domjudge']
    tags:
        - { name: twig.extension }

  domjudge.user_registration_validator:
    class: DOMJudgeBundle\Validator\Constraints\UserRegistrationValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: validator.constraint_validator }

  domjudge.api_headers_listener:
    class: DOMJudgeBundle\EventListener\ApiHeadersListener
    tags:
      - name: kernel.event_listener
        event: kernel.response
        method: onKernelResponse
