name: Check autoconf (Other distros)
on:
  merge_group:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'
    paths:
      - 'configure.ac'
      - 'm4/**'
      - 'Makefile*'
      - '**/Makefile'
      - 'paths.mk.in'
      - 'bootstrap'
      - '.github/workflows/autoconf-check*.yml'
      - '.github/jobs/configure-checks/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  redhat-family:
    strategy:
      matrix:
        version: [latest]
        os: [fedora]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}:${{ matrix.version }}
    steps:
      - name: Install necessary tools
        run: dnf install -y awk git
      - uses: actions/checkout@v4
      - name: Setup image and run bats tests
        run: .github/jobs/configure-checks/setup_configure_image.sh
