name: Check autoconf (Other distros)
on:
  merge_group:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'

jobs:
  redhat-family:
    strategy:
      matrix:
        version: [latest]
        os: [fedora]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}:${{ matrix.version }}
    steps:
      - name: Install necessary tools
        run: dnf install -y awk git
      - uses: actions/checkout@v4
      - name: Setup image and run bats tests
        run: .github/jobs/configure-checks/setup_configure_image.sh
