name: Check autoconf
on:
  merge_group:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'
    paths:
      - 'configure.ac'
      - 'm4/**'
      - 'Makefile*'
      - '**/Makefile'
      - 'paths.mk.in'
      - 'bootstrap'
      - '.github/workflows/autoconf-check*.yml'
      - '.github/jobs/configure-checks/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mainstream:
    strategy:
      matrix:
        version: [noble, rolling]
        os: [ubuntu]
        releaseBranch:
          - ${{ contains(github.ref, 'gh-readonly-queue') }}
        exclude:
          - releaseBranch: false
        include:
          - os: debian
            version: stable
          - os: debian
            version: testing
          - os: fedora
            version: latest
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:
      - uses: actions/checkout@v4
      - name: Run check in OS containers
        run: |
          mkdir -p /tmp/bats_logs/{gcc,all}
          docker run --name preinstall \
            -v "$(pwd):$(pwd)" -w "$(pwd)" ${{ matrix.os}}:${{ matrix.version }} \
            $(pwd)/.github/jobs/configure-checks/setup_configure_image.sh 
          docker commit preinstall baseimage
          docker run --name gcc         -v /tmp/bats_logs/gcc:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "gcc"
          docker run --name all         -v /tmp/bats_logs/all:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "all"
      - name: Upload all logs/artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.version }}-logs
          path: |
            /tmp/bats_logs
