name: Check autoconf
on:
  merge_group:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mainstream:
    strategy:
      matrix:
        version: [noble, rolling]
        os: [ubuntu]
        releaseBranch:
          - ${{ contains(github.ref, 'gh-readonly-queue') }}
        exclude:
          - releaseBranch: false
        include:
          - os: debian
            version: stable
          - os: debian
            version: testing
          - os: fedora
            version: latest
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:
      - uses: actions/checkout@v4
      - name: Run check in OS containers
        run: |
          mkdir -p /tmp/bats_logs/{gcc,gpp,clang,apache,nginx,cgroup,all}
          docker run --name preinstall \
            -v "$(pwd):$(pwd)" -w "$(pwd)" ${{ matrix.os}}:${{ matrix.version }} \
            $(pwd)/.github/jobs/configure-checks/setup_configure_image.sh 
          docker commit preinstall baseimage
          echo "Start GCC check"
          docker run --name gcc         -v /tmp/bats_logs/gcc:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "gcc"
          echo "Start G++ check"
          docker run --name gpp         -v /tmp/bats_logs/gpp:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "gpp"
          echo "Start Clang check"
          docker run --name clang       -v /tmp/bats_logs/clang:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "clang"
          echo "Start Apache check"
          docker run --name apache      -v /tmp/bats_logs/apache:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "apache"
          echo "Start Nginx check"
          docker run --name nginx       -v /tmp/bats_logs/nginx:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "nginx"
          echo "Start LibCgroup check"
          docker run --name cgroup      -v /tmp/bats_logs/cgroup:/tmp/bats_logs \
            -v "$(pwd):$(pwd)" -w "$(pwd)" baseimage \
            $(pwd)/.github/jobs/configure-checks/run_bats.sh "cgroup"
          echo "Start all other checks"
      - name: Upload all logs/artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.version }}-logs
          path: |
            /tmp/bats_logs
