name: Check autoconf
on:
  workflow_call:

jobs:
  mainstream:
    strategy:
      matrix:
        version: [noble, rolling]
        os: [ubuntu]
        releaseBranch:
          - ${{ contains(github.ref, 'gh-readonly-queue') }}
        exclude:
          - releaseBranch: false
        include:
          - os: debian
            version: stable
          - os: debian
            version: testing
          - os: fedora
            version: latest
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:
      - uses: actions/checkout@v4
      - name: Create intermediate container with required tools installed
        run: |
          mkdir -p /tmp/bats_logs/{gcc,gpp,clang,apache,nginx,cgroup}
          docker run --name preinstall \
            -v "$(pwd):$(pwd)" -w "$(pwd)" ${{ matrix.os}}:${{ matrix.version }} \
            $(pwd)/.github/jobs/configure-checks/setup_configure_image.sh 
          docker commit preinstall baseimage
      - name: Run configure checks in parallel
        run: .github/jobs/configure-checks/run_parallel.sh gcc gpp clang apache nginx cgroup
      - name: Upload all logs/artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.version }}-logs
          path: |
            /tmp/bats_logs

  mainstream-gate:
    name: mainstream-gate
    needs: mainstream
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check matrix status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: |
          echo "One or more matrix jobs failed or were cancelled."
          exit 1
      - name: Success
        run: echo "All required jobs passed or were intentionally skipped."
