name: DevSkim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '38 23 * * 1'

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        with:
          ignore-globs: **/*,**,*,**/.github/workflows/*.yml,.github/workflows/mayhem-api.yml,.github/workflows/*.yml

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif

      - uses: actions/upload-artifact@v2
        with:
         name: devskim.sarif
         path: devskim-results.sarif
