name: "Mayhem API analysis"

on:
  schedule:
    - cron: '5 21 * * *'

jobs:
  mayhem:
    name: Mayhem API analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      DB_DATABASE: domjudge
      DB_USER: user
      DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v2

      - name: Install DOMjudge
        run: .github/workflowscripts/baseinstall.sh

      - name: Dump the OpenAPI
        run: ./github/workflowscripts/getapi.sh

      - name: Mayhem for API
        uses: ForAllSecure/mapi-action@193b709971cc377675e33284aecbf9229853e010
        continue-on-error: true
        with:
          mapi-token: ${{ secrets.MAPI_TOKEN }}
          api-url: http://localhost/domjudge/api # <- ✏️ update this
          api-spec: http://localhost/domjudge/api/doc.json # <- ✏️ update this
          duration: 60
          sarif-report: mapi.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: mapi.sarif
