name: Run PHPStan
on:
  merge_group:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'
    paths:
      - 'webapp/**'
      - 'phpstan.dist.neon'
      - 'Makefile*'
      - 'configure.ac'
      - 'm4/**'
      - '.github/workflows/phpstan.yml'
      - '.github/jobs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: domjudge/gitlabci:24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: webapp/vendor
          key: composer-${{ hashFiles('webapp/composer.lock') }}
          restore-keys: |
            composer-
      - name: Setup composer dependencies
        run: .github/jobs/composer_setup.sh
      - name: Show the phpstan version
        run: webapp/vendor/phpstan/phpstan/phpstan --version
      - name: Do basic installation
        run: |
          make inplace-conf CONFIGURE_FLAGS='--with-domjudge-user=root'
          make inplace-install
      - name: Run PHPStan in the classic way
        shell: bash
        run: |
          set -euo pipefail
          webapp/vendor/bin/phpstan \
            --configuration=phpstan.dist.neon \
            --error-format=github \
          | tee /tmp/artifacts/phpstan.out
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: /tmp/artifacts
