name: Qodana
on:
  push:
    branches:
      - qodana_second_try
  #merge_group:
  #pull_request:
  #  branches:
  #    - main
  #    - '[0-9]+.[0-9]+'

jobs:
  # TODO: https://github.com/JetBrains/qodana-action
  # We can open a PR with fixes to the found issues
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.3
        with:
          upload-result: true
          post-pr-comment: false
          pr-mode: false # Change after the sarif file
          args: --baseline,qodana.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
