name: Webstandard (WCAG, W3C)
on:
  merge_group:
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  standards:
    runs-on: ubuntu-latest
    env:
      ADMIN_PASSWORD: admin_password
      MYSQL_ROOT_PASSWORD: mysql_root_password
    container:
      image: domjudge/gitlabci:24.04
    services:
      sqlserver:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        role: [public, team, balloon, jury, admin]
        test: [w3cval, WCAG2A, WCAG2AA]
        db: [bare-install, install]
        exclude:
          - role: jury
            test: WCAG2AA
          - role: jury
            test: WCAG2A
          - role: admin
            test: WCAG2AA
          - role: admin
            test: WCAG2A
          - role: public
            test: WCAG2A
          - role: balloon
            test: WCAG2A
          - role: team
            test: WCAG2A
    steps:
      - uses: actions/checkout@v4
      - name: Compute condition
        id: filter
        run: |
          filter_out() {
            if [ "${{ matrix.db }}" = "bare-install" ]; then
                echo "should_run=false" >> $GITHUB_OUTPUT
            elif [ "${{ matrix.role }}" = "public" ]; then
              if [ "${{ matrix.test }}" = "WCAG2A" ]; then
                echo "should_run=false" >> $GITHUB_OUTPUT
              else
                echo "should_run=true" >> $GITHUB_OUTPUT
              fi
            elif [ "${{ matrix.role }}" = "balloon" ]; then
              echo "should_run=false" >> $GITHUB_OUTPUT
            elif [ "${{ matrix.role }}" = "jury" ]; then
              echo "should_run=false" >> $GITHUB_OUTPUT
            elif [ "${{ matrix.role }}" = "admin" ]; then
              if [ "${{ matrix.test }}" = "w3cval" ]; then
                echo "should_run=true" >> $GITHUB_OUTPUT
              else
                echo "should_run=true" >> $GITHUB_OUTPUT
              fi
            else
              # Should never happen
              echo "should_run=true" >> $GITHUB_OUTPUT
            fi
          }

          if [[ "${GITHUB_EVENT_NAME}" == "merge_group" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            filter_out
          elif [[ "${GITHUB_EVENT_NAME}" == "push" ]] &&
               [[ "${GITHUB_REPOSITORY}" == "DOMjudge/domjudge" ]] &&
               [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            filter_out
          fi
      - name: Mark as skipped
        if: steps.filter.outputs.should_run == 'false'
        run: echo "Skip job"
      - name: Cache node modules
        if: steps.filter.outputs.should_run == 'true'
        uses: actions/cache@v4
        with:
          path: webapp/node_modules
          key: npm-${{ hashFiles('webapp/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Cache composer dependencies
        if: steps.filter.outputs.should_run == 'true'
        uses: actions/cache@v4
        with:
          path: webapp/vendor
          key: composer-${{ hashFiles('webapp/composer.lock') }}
          restore-keys: |
            composer-
      - name: Install DOMjudge
        if: steps.filter.outputs.should_run == 'true'
        run: .github/jobs/baseinstall.sh ${{ matrix.role }} ${{ matrix.db }}
      - name: Run webstandard tests (W3C, WCAG)
        if: steps.filter.outputs.should_run == 'true'
        run: .github/jobs/webstandard.sh ${{ matrix.test }} ${{ matrix.role }}
      - name: Upload database dump for debugging
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: DB-dump${{ matrix.artifact_suffix }}
          path: /tmp/artifacts/db.sql
      - name: Upload all logs/artifacts
        if: ${{ steps.filter.outputs.should_run == 'true' && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-${{ matrix.test }}-${{ matrix.db }}-logs
          path: |
            /tmp/artifacts
            /var/log/nginx
            /opt/domjudge/domserver/webapp/var/log/*.log
